const Status = {
	NOT_STARTED: 'notStarted',
	STARTED: 'started',
	FINISHED: 'finished'
};

export default {
	STATUS: Status,
	SET_STATUS: 'QUIZ_SET_STATUS',
	SET_QUESTION_IDS: 'QUIZ_SET_QUESTION_IDS',
	SET_REMOTE_ACTIVE_QUESTION_ID: 'QUIZ_SET_REMOTE_ACTIVE_QUESTION_ID',
	SET_LOCAL_ACTIVE_QUESTION_ID: 'QUIZ_SET_LOCAL_ACTIVE_QUESTION_ID',
	SET_ACTIVE_QUESTION: 'QUIZ_SET_ACTIVE_QUESTION',
	UPDATE_ACTIVE_QUESTION: 'QUIZ_UPDATE_ACTIVE_QUESTION',
	SET_ONLINE_USERS_COUNT: 'QUIZ_SET_ONLINE_USERS_COUNT',
	SET_RESULTS: 'QUIZ_SET_RESULTS'
};
