const Status = {
	NOT_STARTED: 'notStarted',
	STARTED: 'started',
	FINISHED: 'finished'
};

export default {
	STATUS: Status,
	SET_STATUS: 'QUIZ_SET_STATUS',
	SET_QUESTION_IDS: 'QUIZ_SET_QUESTION_IDS',
	SET_ACTIVE_QUESTION: 'QUIZ_SET_ACTIVE_QUESTION',
	SET_ACTIVE_QUESTION_VOTE: 'QUIZ_SET_ACTIVE_QUESTION_VOTE',
	SET_ACTIVE_QUESTION_VOTES: 'QUIZ_SET_ACTIVE_QUESTION_VOTES',
	SET_ONLINE_USERS_COUNT: 'QUIZ_SET_ONLINE_USERS_COUNT'
};
